### ISSUE TITLE
Problema para rodar projeto

### ISSUE THREAD

**Issue by marcelovieiratecnologia** [treinaweb/treinaweb-django-orm-parte-1#1]
Olá, tudo bem 

Desculpe mas estou com dificuldades em rodar o projeto, cara hora pede uma coisa , problemas com adminlte/base.html eu acerto ai pede o helpers tb , será que comecei errado 

Tem instruções para fazer rodar

**Comment by wladimilson** [comment]
Olá,

Sim, este ponto é explicado no curso de onde este código é proveniente: https://www.treinaweb.com.br/curso/django-banco-de-dados-com-django-orm-parte-1

Caso seja um dos nossos alunos, os instrutores do curso no nosso sistema de suporte também podem lhe auxiliar neste processo.

De qualquer forma, para rodar a aplicação, você precisa ter instalado no seu ambiente os módulos: django, django-adminlte2 e mysqlclient.

**Comment by marcelovieiratecnologia** [comment]
Entendi, não sou aluno, mas mesmo assim , obrigado !

**Comment by wladimilson** [comment]
De nada :)
